[package]
name = "debug2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive = { path = "./derive" }

[dev-dependencies]
insta = "1.7.1"

[workspace]
members = [
    ".",
    "./derive"
]